name: YDB tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
    - cron: '18 4 * * *'

env:
  CARGO_TERM_COLOR: always
  CARGO_REGISTRIES_CRATES_IO_PROTOCOL: sparse
  RUST_VERSION_OLD: "1.81.0"
  RUST_VERSION_NEW: "1.86.0"

jobs:
  tests:
    strategy:
      fail-fast: false
      matrix:
        rust_version: [ "RUST_VERSION_OLD", "RUST_VERSION_NEW" ]

    services:
      ydb:
        image: cr.yandex/yc/yandex-docker-local-ydb:latest
        ports:
          - 2135:2135
          - 2136:2136
          - 8765:8765
        volumes:
          - /tmp/ydb_certs:/ydb_certs
        env:
          YDB_USE_IN_MEMORY_PDISKS: true
        options: '-h localhost --name ydb'

    runs-on: ubuntu-24.04

    steps:
    - name: Show YDB server version
      run: docker ps; docker exec ydb /ydbd -V

    - name: Install stable rust
      uses: dtolnay/rust-toolchain@v1
      with:
        toolchain: ${{ env[matrix.rust_version] }}
        components: clippy, rustfmt

    - name: Install nightly rust
      if: matrix.rust_version == 'RUST_VERSION_NEW'
      uses: dtolnay/rust-toolchain@v1
      with:
        toolchain: nightly
        components: clippy, rustfmt

    - name: Cargo install
      if: matrix.rust_version == 'RUST_VERSION_NEW'
      run: cargo install cargo-sort cargo-udeps cargo-audit cargo-pants

    - name: Checkout
      uses: actions/checkout@v4
      with:
        submodules: true

    - name: Rust version
      id: rust_version_step
      run: |
        rustc --version
        cargo --version
        echo "CARGO_INCREMENTAL=$CARGO_INCREMENTAL"
        echo "name=version::$(rustc --version | cut -d ' ' -f 2)" >> $GITHUB_OUTPUT

    - name: Rust cache
      uses: Swatinem/rust-cache@v2

    - name: Rustfmt check
      if: matrix.rust_version == 'RUST_VERSION_NEW'
      run: cargo fmt --check

    - name: Cargo sort check
      if: matrix.rust_version == 'RUST_VERSION_NEW'
      run: cargo sort --workspace --check

    - name: Cargo udeps check
      if: matrix.rust_version == 'RUST_VERSION_NEW'
      run: cargo +nightly udeps --all-targets

    - name: Security check
      if: matrix.rust_version == 'RUST_VERSION_NEW'
      run: cargo audit && cargo pants

    - name: Run tests
      env:
        YDB_CONNECTION_STRING: grpc://localhost:2136?database=/local
      run: cargo test --verbose --workspace -- --include-ignored

    - name: Linter
      if: matrix.rust_version == 'RUST_VERSION_NEW'
      run: |
        cargo clippy --workspace --all-targets --no-deps --exclude=ydb-grpc -- -D warnings
